### ISSUE TITLE
multiqueue/multiqueue.h missing

### ISSUE THREAD

**Issue by kjellwinblad** [jkopinsky/SprayList#2]
Git commit id: 6ac7bf83c4b619aee858351789e988519c99d98b

It seems like a file is missing. The following error message is printed when compiling with make:

sssp.c:14:35: fatal error: multiqueue/multiqueue.h: No such file or directory

**Comment by jkopinsky** [comment]
Oops, I don't actually have any licensing for Multiqueues so I can't include their code. The harness code which we used to compare to MQs was pushed accidentally, but should be gone now, sorry for the confusion!
